export const projects = [
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing Website",
    desc: "3D Printing website catalog",
  },
  {
    imgSrc: "/projectImg/PokemonMemoryGame.jpeg",
    tag1: "REACT",
    tag2: "TAILWIND",
    tag3: "JAVASCRIPT",
    name: "Pokemon Memory Game",
    desc: "Card memory game that test your memorization skill",
  },
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing Website",
    desc: "3D Printing website catalog",
  },
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing Website",
    desc: "3D Printing website catalog",
  },
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing Website",
    desc: "3D Printing website catalog",
  },
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing Website",
    desc: "3D Printing website catalog",
  },
];
