export const projects = [
  {
    imgSrc: "/projectImg/printForge.jpeg",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Print Forge 3D printing website",
    desc: "3D Printing website catalog. Features product filtering, search functionality.",
  },
  {
    imgSrc: "/projectImg/PokemonMemoryGame.jpeg",
    tag1: "REACT",
    tag2: "TAILWIND",
    tag3: "JAVASCRIPT",
    name: "Pokemon memory game",
    desc: "Card memory game that test your memorization skill",
  },
  {
    imgSrc: "/projectImg/toko-hero.jpg",
    tag1: "ASTRO",
    tag2: "TAILWIND",
    tag3: "JAVASCRIPT",
    name: "Grocery store catalog website",
    desc: "A responsive e-commerce catalog website for a local grocery store. Features product filtering, search functionality.",
  },
  {
    imgSrc: "/projectImg/worlde.png",
    tag1: "NEXT.JS",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Assembly: Endgame - Programming Language Word Game",
    desc: "A thrilling word-guessing game where you must guess programming terms before Assembly takes over!",
  },
  {
    imgSrc: "/projectImg/tenzies.jpeg",
    tag1: "REACT",
    tag2: "TAILWIND",
    tag3: "TYPESCRIPT",
    name: "Tenzies Game",
    desc: "A fun React-based dice game where you roll until all 10 dice show the same number. Click to freeze dice between rolls!",
  },
  {
    imgSrc: "/projectImg/comingsoon.png",
    tag1: "FRAMEWORK",
    tag2: "LANGUAGE",
    tag3: "LANGUAGE",
    name: "Coming Soon",
    desc: "Building next beautiful project..",
  },
];
